#ifndef _MVISOR_FVP_CONFIG_H_
#define _MVISOR_FVP_CONFIG_H_

#define CONFIG_RAM_START_ADDRESS	0x80000000
#define CONFIG_RAM_SIZE			0x80000000

#define CONFIG_MVISOR_START_ADDRESS	(0xc0000000)
#define CONFIG_MVISOR_RAM_SIZE		(64 * 1024 *1024)

#define CONFIG_MAX_CPU_NR		(8)
#define CONFIG_NR_CPUS			(4)
#define CONFIG_VM_MAX_VCPU		(CONFIG_NR_CPUS)
#define CONFIG_MAX_VM			(4)

#define CONFIG_IRQ_CHIP_NAME		"gicv3"
#define CONFIG_MMU_CHIP_NAME		"armv8-mmu"

#define CONFIG_LOG_LEVEL		4

#define CONFIG_ARM_AARCH64		1
#define CONFIG_ARCH_ARMV8_A		1

#define CONFIG_MAX_PHYSICAL_SIZE	(0x100000000)

#define CONFIG_SCHED_INTERVAL		(20)

#define CONFIG_GRANULE_SIZE_64K

#define CONFIG_MVISOR_MM_SIMPLE_MODE

#define CONFIG_VCPU_MAX_ACTIVE_IRQS	(16)

#define CONFIG_MVISOR_RESCHED_IRQ	(13)

#include <config/common.h>

#endif
