obj-y += foundation-v8-gicv2.dtb
obj-y += foundation-v8-gicv3.dtb
obj-y += bcm2837-rpi-3-b-plus.dtb
obj-y += armada-3720-community-v5.dtb
obj-y += bcm2838-rpi-4-b.dtb
obj-y += bcm2838-rpi-4-b-32bit.dtb
obj-y += kvim3.dtb
