#ifndef _MINOS_FVP_CONFIG_H_
#define _MINOS_FVP_CONFIG_H_

#define ARCH_AARCH64
#define CONFIG_PLATFORM_ARMADA

#define CONFIG_RAM_START_ADDRESS	0x00000000
#define CONFIG_RAM_SIZE			0x40000000

#define CONFIG_MINOS_START_ADDRESS	(0x3c000000)
#define CONFIG_MINOS_RAM_SIZE		(64 * 1024 *1024)

#define CONFIG_MAX_CPU_NR		(8)
#define CONFIG_NR_CPUS			(2)
#define CONFIG_NR_CPUS_CLUSTER0		(2)
#define CONFIG_NR_CPUS_CLUSTER1		(0)
#define CONFIG_MAX_VM			(64)

#define CONFIG_PLATFORM_NAME		"marvel_armada"

#define CONFIG_LOG_LEVEL		3

#define CONFIG_SCHED_INTERVAL		(20)

#define CONFIG_VCPU_MAX_ACTIVE_IRQS	(16)

#define CONFIG_MINOS_RESCHED_IRQ	(7)

#define CONFIG_MAX_SLAB_BLOCKS		(4)

#define CONFIG_UART_BASE		(0xd0012000)
#define CONFIG_UART_IO_SIZE		(0x40000)

#define CONFIG_PLATFORM_ADDRESS_RANGE	(40)
#define CONFIG_PLATFORM_IO_BASE		(0xd0000000UL)
#define CONFIG_PLATFORM_DRAM_BASE	(0x00000000UL)

#define CONFIG_BOOTMEM_SIZE		(64 * 1024)
#define IDLE_VCPU_STATCK_SIZE		(8 * 1024)
#define IDLE_VCPU_STATCK_SHIFT		(13)

#endif
