obj-y += platform.o
obj-$(CONFIG_SOC_MARVELL_A3700)	+= espressobin/
obj-$(CONFIG_SOC_FVP) 	   	+= fvp/
obj-$(CONFIG_SOC_BCM2837)  	+= raspberry3/
obj-$(CONFIG_SOC_BCM2838)  	+= raspberry4/
obj-$(CONFIG_SOC_AMLOGIC)  	+= amlogic/
obj-$(CONFIG_SOC_R8A7795)	+= r8a7795/
