#ifndef __MINOS_CONFIG_H__
#define __MINOS_CONFIG_H__

#define CONFIG_ARCH_AARCH64 1
#define CONFIG_DEVICE_TREE 1
#define CONFIG_PLATFORM_FVP 1
#define CONFIG_SERIAL_PL011 1
#define CONFIG_IRQCHIP_GICV3 1
#define CONFIG_IRQCHIP_GICV2 1
#define CONFIG_VIRQCHIP_VGICV2 1
#define CONFIG_VIRQCHIP_VGICV3 1
#define CONFIG_VIRTIO_MMIO 1
#define CONFIG_VRTC_PL031 1
#define CONFIG_VWDT_SP805 1
#define CONFIG_RAM_START_ADDRESS 0x80000000
#define CONFIG_RAM_SIZE 0x80000000
#define CONFIG_MINOS_START_ADDRESS 0xc0000000
#define CONFIG_MINOS_RAM_SIZE 0x4000000
#define CONFIG_MAX_CPU_NR 8
#define CONFIG_NR_CPUS 4
#define CONFIG_NR_CPUS_CLUSTER0 4
#define CONFIG_NR_CPUS_CLUSTER1 0
#define CONFIG_UART_BASE 0x1c090000
#define CONFIG_UART_IO_SIZE 0x40000
#define CONFIG_PLATFORM_ADDRESS_RANGE 40
#define CONFIG_TASK_DEFAULT_STACK_SIZE 0x1000
#define CONFIG_IDLE_TASK_STACK_SHIFT 12
#define CONFIG_MAX_MAILBOX_NR 10
#define CONFIG_BOOTMEM_SIZE 0x10000
#define CONFIG_MAX_VM 64
#define CONFIG_IDLE_VCPU_STACK_SHIFT 13
#define CONFIG_SCHED_INTERVAL 50
#define CONFIG_MAX_SLAB_BLOCKS 10
#define CONFIG_LOG_LEVEL 3
#define CONFIG_MINOS_RESCHED_IRQ 7
#define CONFIG_IDLE_VCPU_STACK_SIZE 0x2000

#endif