obj-$(CONFIG_VIRQCHIP_BCM2836)	+= bcm_virq.o
obj-$(CONFIG_VIRQCHIP_VGICV2)	+= vgicv2.o
obj-$(CONFIG_VIRQCHIP_VGICV3)	+= vgicv3.o
obj-$(CONFIG_VIRTIO_MMIO)	+= virtio_mmio.o
obj-$(CONFIG_VRTC_PL031)	+= vrtc.o
obj-$(CONFIG_VWDT_SP805)	+= vwdt.o
