#ifndef _MINOS_FVP_CONFIG_H_
#define _MINOS_FVP_CONFIG_H_

#define ARCH_AARCH64
#define CONFIG_PLATFORM_FVP

#define CONFIG_RAM_START_ADDRESS	0x80000000
#define CONFIG_RAM_SIZE			0x80000000

#define CONFIG_MINOS_START_ADDRESS	(0xc0000000)
#define CONFIG_MINOS_RAM_SIZE		(1024 * 1024 *1024)

#define CONFIG_MAX_CPU_NR		(8)
#define CONFIG_NR_CPUS			(4)
#define CONFIG_VM_MAX_VCPU		(CONFIG_NR_CPUS)
#define CONFIG_MAX_VM			(64)

#define CONFIG_IRQ_CHIP_NAME		"gicv3"
#define CONFIG_MMU_CHIP_NAME		"armv8-mmu"

#define CONFIG_LOG_LEVEL		3

#define CONFIG_SCHED_INTERVAL		(20)

#define CONFIG_VCPU_MAX_ACTIVE_IRQS	(16)

#define CONFIG_MINOS_RESCHED_IRQ	(13)

#define CONFIG_MAX_SLAB_BLOCKS		(10)

#define CONFIG_UART_BASE		(0x1c090000)
#define CONFIG_UART_IO_SIZE		(0x40000)

#define CONFIG_PLATFORM_ADDRESS_RANGE	(40)
#define CONFIG_PLATFORM_IO_BASE		(0x0UL)
#define CONFIG_PLATFORM_DRAM_BASE	(0x80000000)

#endif
